datasets:
  A:
    hf_id: CANON.DATASET.A.HF_ID
    config: CANON.DATASET.A.HF_CONFIG
    split: CANON.DATASET.A.SPLIT
  B:
    hf_id: CANON.DATASET.B.HF_ID
    config: CANON.DATASET.B.HF_CONFIG
    split: CANON.DATASET.B.SPLIT
  ARC_MCQ:
    hf_id: CANON.DATASET.ARC_MCQ.HF_ID
    config: CANON.DATASET.ARC_MCQ.HF_CONFIG
    split: CANON.DATASET.ARC_MCQ.SPLIT
